In [3]:
import numpy as np

In [7]:
array = np.array([2,2])
array

array([2, 2])

In [8]:
#create a two dimensional array using numpy

two_d_arr = np.array([[2,3,3],[3,5,6]])
two_d_arr

array([[2, 3, 3],
       [3, 5, 6]])

## reshape a array 

In [14]:
a = np.arange(15).reshape(3, 5)

In [15]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])