In [3]:
import numpy as np

In [5]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) 

[7 8 9]


In [7]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a[1,1]

6

In [9]:
matrix = np.array([[7,8],[4,5]])
matrix

array([[7, 8],
       [4, 5]])

In [12]:
matrix.size

4

In [13]:
matrix.shape

(2, 2)

In [17]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
arr.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [22]:
import torch

In [26]:
rand_t = torch.rand(4,4)
rand_t

tensor([[0.3509, 0.3242, 0.2006, 0.1567],
        [0.9605, 0.8485, 0.9573, 0.2221],
        [0.0766, 0.6933, 0.7809, 0.3957],
        [0.6375, 0.5099, 0.0433, 0.2147]])

In [25]:
rand_arr = rand_t.numpy()
rand_arr

array([[0.9611747 , 0.1239633 , 0.30539984, 0.3141117 ],
       [0.9130755 , 0.92625564, 0.2942884 , 0.23156309],
       [0.8604968 , 0.84485775, 0.9687368 , 0.5005172 ],
       [0.8517055 , 0.5756996 , 0.12685531, 0.32010734]], dtype=float32)

In [30]:
arr2 = arr.reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
rand_arr + arr2

array([[ 0.96117473,  1.1239633 ,  2.30539984,  3.31411171],
       [ 4.91307551,  5.92625564,  6.2942884 ,  7.23156309],
       [ 8.86049682,  9.84485775, 10.96873683, 11.50051719],
       [12.85170549, 13.57569963, 14.12685531, 15.32010734]])

In [32]:
rand_arr - 2 

array([[-1.0388253, -1.8760366, -1.6946001, -1.6858883],
       [-1.0869246, -1.0737443, -1.7057116, -1.7684369],
       [-1.1395032, -1.1551423, -1.0312631, -1.4994829],
       [-1.1482944, -1.4243004, -1.8731446, -1.6798927]], dtype=float32)

In [33]:
rand_arr / 2

array([[0.48058736, 0.06198165, 0.15269992, 0.15705585],
       [0.45653775, 0.46312782, 0.1471442 , 0.11578155],
       [0.4302484 , 0.42242888, 0.4843684 , 0.2502586 ],
       [0.42585275, 0.2878498 , 0.06342766, 0.16005367]], dtype=float32)

In [39]:
arr_rand = np.random.rand(4,4)
arr_rand

array([[0.37366412, 0.4182999 , 0.36142672, 0.06327799],
       [0.00410725, 0.37404106, 0.50042644, 0.58695583],
       [0.93590916, 0.16195835, 0.58230187, 0.48688264],
       [0.56690478, 0.39708198, 0.22584051, 0.4819807 ]])

In [37]:
arr_rand = [1,2,3,4] * arr_rand
arr_rand


array([[ 0.79455695,  0.40332116,  5.76087729,  6.19255   ],
       [ 0.98954195,  1.62450816,  1.56157735,  4.91531453],
       [ 0.70943004,  2.88879714,  8.45933601, 15.49382567],
       [ 0.49894036,  1.54387949,  5.56850852, 11.38220489]])

In [38]:
np.stack((arr_rand,arr2),axis=0)

array([[[ 0.79455695,  0.40332116,  5.76087729,  6.19255   ],
        [ 0.98954195,  1.62450816,  1.56157735,  4.91531453],
        [ 0.70943004,  2.88879714,  8.45933601, 15.49382567],
        [ 0.49894036,  1.54387949,  5.56850852, 11.38220489]],

       [[ 0.        ,  1.        ,  2.        ,  3.        ],
        [ 4.        ,  5.        ,  6.        ,  7.        ],
        [ 8.        ,  9.        , 10.        , 11.        ],
        [12.        , 13.        , 14.        , 15.        ]]])

In [45]:
print(arr_rand)
np.sum(arr_rand)

[[0.37366412 0.4182999  0.36142672 0.06327799]
 [0.00410725 0.37404106 0.50042644 0.58695583]
 [0.93590916 0.16195835 0.58230187 0.48688264]
 [0.56690478 0.39708198 0.22584051 0.4819807 ]]


6.5210593027177906

In [46]:
np.min(arr_rand)

0.004107247241580403

In [47]:
np.max(arr_rand)

0.9359091595438772

In [48]:
np.mean(arr_rand)

0.4075662064198619